### ISSUE TITLE
Script won't play any key/note more than once 

### ISSUE THREAD

**Issue by m4xolotl** [3096/genshin_scripts#1]
it won't play any note after it has already been played previously
So a sequence of CDCFGAB CDEFGAB becomes CD_FGAB _ _E_ _ _ _

**Comment by m4xolotl** [comment]
it took me hours to realise what was the problem, i initially thought the script wasn't playing anything beyond the first bar (because i made a test midi of just a C major scale of 7 notes), but then realised it wasn't playing a key that had already been played after randomly testing a midi of CBCEFGABD and the D still played at the end

**Comment by m4xolotl** [comment]
This is the output when testing in notepad; assaaffgghhjjqqaassddffgghhjjqq

2 issues here; Every note after the 1st seems to be duplicated. Also the second C is showing up in the output as the "aa" after the "ss", but it isn't playing in actual Genshin...

strange

**Comment by 3096** [comment]
Yeah when the key is already pressed and there's an overlap, the current setup doesn't actually press it again. I'll look into this

**Comment by 3096** [comment]
aight I pushed a change that adds a config to only briefly click each note. does it solve the missing notes issue?
