### ISSUE TITLE
Midi Config File?

### ISSUE THREAD

**Issue by Skitto493** [3096/genshin_scripts#2]
Hello,

I noticed that the script requires a "midi_config.json", but that file isn't included in the repository.

Is there a certain way the json file should be formatted if I do have to write it myself?

**Comment by takan251147** [comment]
i have same issues

**Comment by Skitto493** [comment]
Managed to figure it out!
{
    "songs": [
        {
            "file": "bad_apple.mid",
            "key" :  "1"
        }
    ]
}

this one worked for me. The "key' is the key you press along with tab to start the song. File is the filename (if it's in the same folder as the script).

**Comment by 3096** [comment]
oh yeah I have a template json that I haven't pushed yet. Plus I'm lacking some documentation too. Should all come in due time tho

**Comment by Djengu** [comment]
Hello! Sorry I'm new to this, I was interested in using your script to try out some midi files on genshin! I have the midi file in the same directory and am using bad_apple.mid under key: 1 on your json template, how do I get the script to start running though? 

![jsontestimg](https://user-images.githubusercontent.com/81548080/112788550-fb4d7a00-900f-11eb-8433-f979f04d664a.png)
![lyrehelp](https://user-images.githubusercontent.com/81548080/112788551-fb4d7a00-900f-11eb-9b63-6e9319145268.png)

**Comment by 3096** [comment]
> Hello! Sorry I'm new to this, I was interested in using your script to try out some midi files on genshin! I have the midi file in the same directory and am using bad_apple.mid under key: 1 on your json template, how do I get the script to start running though?
> 
> ![jsontestimg](https://user-images.githubusercontent.com/81548080/112788550-fb4d7a00-900f-11eb-8433-f979f04d664a.png)
> ![lyrehelp](https://user-images.githubusercontent.com/81548080/112788551-fb4d7a00-900f-11eb-9b63-6e9319145268.png)

you should just be able to run the midi.py python script given you have the dependencies installed. This is offtopic here tho.
If you don't know how you could wait for the tutorial I'm planning on making tomorrow.

**Comment by 3096** [comment]
closing this as https://github.com/3096/genshin_scripts/commit/bd61037421c41f4382f6acc49ee735aeb222e4c9 added the template
