### ISSUE TITLE
I got some error !

### ISSUE THREAD

**Issue by IonZery** [3096/genshin_scripts#3]
![image](https://user-images.githubusercontent.com/46859662/112791799-72285880-908c-11eb-8a3f-dfbac0d0869e.png)

**Comment by jgyy** [comment]
pip install mido

**Comment by IonZery** [comment]
> pip install mido

i have already installed

**Comment by Sodiumchloridy** [comment]
have you added the midi path to json file?

**Comment by jgyy** [comment]
Sorry cant replicate your issue

pip show mido

Name: mido
Version: 1.2.9
Summary: MIDI Objects for Python
Home-page: https://mido.readthedocs.io/
Author: Ole Martin Bjorndalen
Author-email: ombdalen@gmail.com
License: MIT
Location: c:\python39\lib\site-packages
Requires:
Required-by:

I see no issue with my midi package

**Comment by IonZery** [comment]
> have you added the midi path to json file?

yes !

**Comment by Sodiumchloridy** [comment]
remove and reinstall mido maybe?

**Comment by IonZery** [comment]
![image](https://user-images.githubusercontent.com/46859662/112793074-d0eed180-908e-11eb-942e-8484661393c7.png)
how LOL

**Comment by jgyy** [comment]
seems like your json file formatting got issue?

**Comment by IonZery** [comment]
> seems like your json file formatting got issue?

idk :(

**Comment by 3096** [comment]
if you have a windows path, you need to use double backslashes in json
like this: `D:\\bruh\\moment.mid`

**Comment by IonZery** [comment]
> if you have a windows path, you need to use double backslashes in json
> like this: `D:\\bruh\\moment.mid`

okay thk i will try it

**Comment by jgyy** [comment]
> if you have a windows path, you need to use double backslashes in json
> like this: `D:\\bruh\\moment.mid`

erm for the file path in python, cant the code just accepts raw string instead? Cause I feel that end user should not be concerned with escape characters.

**Comment by IonZery** [comment]
> if you have a windows path, you need to use double backslashes in json
> like this: `D:\\bruh\\moment.mid`

It worked thk u so much !

**Comment by jgyy** [comment]
> > erm for the file path in python, cant the code just accepts raw string instead? Cause I feel that end user should not be concerned with escape characters.
> 
> I believe that's part of the json standard actually so the built in parser requires escape I think

I recall encountering that problem myself in the past, what I did before json.loads() is to do text.replace('\', '\\') prior to loading it as a dictionary, only if there is an exception. The validation portion is a messy code though.

**Comment by 3096** [comment]
> > > erm for the file path in python, cant the code just accepts raw string instead? Cause I feel that end user should not be concerned with escape characters.
> > 
> > 
> > I believe that's part of the json standard actually so the built in parser requires escape I think
> 
> I recall encountering that problem myself in the past, what I did before json.loads() is to do text.replace('', '\') prior to loading it as a dictionary, only if there is an exception. The validation portion is a messy code though.

I agree. it would also break any case when you do need a \escaped character (although unlikely anyone would actually need one). 

rather undesired

double backslash will probably have to do for now
