### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by s0806774** [3096/genshin_scripts#4]
i  use pycharm  run 
How do i do the next step?
![image](https://user-images.githubusercontent.com/81557679/112811314-84b38980-90ae-11eb-9d68-56139bd49bd9.png)

**Comment by Sodiumchloridy** [comment]
press tab + 1 together

**Comment by SanSan-** [comment]
`START_COMBO_KEY = [pynput.keyboard.Key.tab]` + `key` from `midi_config.json`

in other words: in your case it will be `TAB+1`, cause `th09_04.mid` key is `1` and `START_COMBO_KEY ` is `TAB`

**Comment by jgyy** [comment]
erm you dont need text editor / IDE to run this script. Just install python and run it on the terminal.
