### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by thelazyorange** [3096/genshin_scripts#5]
how to fix this
![mido](https://user-images.githubusercontent.com/80612793/112858588-99ab0f80-90e4-11eb-8b98-e3c645bfadc1.PNG)

**Comment by nyawo** [comment]
you need to install that module, by typing "pip install mido"

**Comment by AnthonySam538** [comment]
It seems they already installed mido. Looking at where pynput and mido are installed, it's definitely a lot different from where mine are installed. Mine are simply installed in `c:\users\antho\appdata\local\programs\python\python39\lib\site-packages`, not `c:\users\carlo\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages`. `pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0` and `localcache` look particularly off to me, but I'm not really sure.

**Comment by thelazyorange** [comment]
works now thanks!
