### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by OmegaZ2** [3096/genshin_scripts#8]
Hello, I'm having this error when I try to press any key on my keyboard. I'm running and building the .py file from sublime text 3. I did pip installed every library that I was missing.
![12](https://user-images.githubusercontent.com/57547652/112905527-f3014780-90c0-11eb-8b23-d147acb641db.PNG)

**Comment by 3096** [comment]
could you provide the midi file that causes the error?

**Comment by OmegaZ2** [comment]
I fixed it, all I did was reinstall the pynput library and the script worked just fine.
